version: '3'
services:
  db:
    build: 
      context: ./postgres # Dockerfile location
      dockerfile: Dockerfile
    ports:
      - "5432:5432" # Maps port 5432 on the host to port 5432 on the service
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  web:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend-service/app
      dockerfile: Dockerfile
    ports:
      - "80:80"